# Generated by Django 6.0.3 on 2026-06-03 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_fixed', models.BooleanField(default=False, help_text='Check if this is a flat amount discount')),
                ('discount', models.IntegerField(help_text='Enter percentage (0-100) or flat amount', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='How many times this coupon can be used total')),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
