# Generated by Django 6.0.3 on 2026-06-13 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_category_uuid_alter_product_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed ₹ amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed ₹ amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('referrer_reward_type', models.CharField(choices=[('WALLET_CREDIT', 'Wallet Credit (₹)'), ('PERCENTAGE', 'Percentage Discount (%)')], default='WALLET_CREDIT', help_text='Reward given to the person who referred.', max_length=20)),
                ('referrer_reward_value', models.DecimalField(decimal_places=2, default=100, help_text='₹ credit or % discount for the referrer.', max_digits=10)),
                ('referee_reward_type', models.CharField(choices=[('WALLET_CREDIT', 'Wallet Credit (₹)'), ('PERCENTAGE', 'Percentage Discount (%)')], default='WALLET_CREDIT', help_text='Reward given to the new user who signed up.', max_length=20)),
                ('referee_reward_value', models.DecimalField(decimal_places=2, default=50, help_text='₹ credit or % discount for the referee.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_offer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_usages', to=settings.AUTH_USER_MODEL)),
                ('referral_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='offers.referraloffer')),
            ],
            options={
                'unique_together': {('referral_offer', 'referee')},
            },
        ),
    ]
