# Generated by Django 6.0.3 on 2026-06-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('REFUND', 'Refund for Cancellation/Return'), ('PURCHASE', 'Order Payment'), ('RECHARGE', 'Wallet Recharge'), ('ADMIN_ADJUST', 'Admin Adjustment')], max_length=20),
        ),
    ]
