# Generated by Django 6.0.3 on 2026-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallettransaction_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
