# Generated by Django 6.0.3 on 2026-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallettransaction_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(choices=[('REFUND', 'Refund for Cancellation/Return'), ('PURCHASE', 'Order Payment'), ('RECHARGE', 'Wallet Recharge'), ('ADMIN_ADJUST', 'Admin Adjustment'), ('REFERRAL_BONUS', 'Referral Bonus')], max_length=20),
        ),
    ]
