# Generated by Django 6.0.3 on 2026-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_applied_coupon_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='admin_return_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('RETURN_REJECTED', 'Return Rejected')], default='ACTIVE', max_length=20),
        ),
    ]
