# Generated by Django 6.0.3 on 2026-05-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_collection_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
