# Generated by Django 6.0.3 on 2026-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_uuid_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='size_ml',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
