# Generated by Django 6.0.3 on 2026-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant_size_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_seasonal',
            field=models.BooleanField(default=False, help_text='Enable automatic activation/archiving based on a recurring annual date window.'),
        ),
        migrations.AddField(
            model_name='category',
            name='season_end_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month the season ends', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month the season ends (1=Jan, 12=Dec)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='season_start_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month the season starts', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month the season starts (1=Jan, 12=Dec)', null=True),
        ),
    ]
